// Tool registry modul
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { isPathAllowed, isUrlSafe } = require('../security/validator');

const toolRegistry = new Map();

function registerTool(name, handler) {
    toolRegistry.set(name, handler);
    console.log(`🔧 Tool regisztrálva: ${name}`);
}

registerTool('file_read', async (input) => {
    if (!isPathAllowed(input.path)) return { error: `Tiltott útvonal: ${input.path}` };
    try {
        const content = fs.readFileSync(input.path, 'utf8');
        return { content, size: content.length };
    } catch (e) { return { error: e.message }; }
});

registerTool('sandbox_write', async (input) => {
  const { filename, content, knowledge_id, purpose } = input;
  if (!filename || !content) return { error: 'Hianyzo parameter: filename, content' };
  
  const path = require('path');
  const fs = require('fs');
  const SANDBOX = path.join(__dirname, '..', 'sandbox');
  
  // Csak sandbox mappaba irhat
  const targetPath = path.join(SANDBOX, path.basename(filename));
  
  // Meta fejlec
  const { RuntimeClient } = require('../runtimeClient');
  const rc = new RuntimeClient();
  const project = await rc.getActiveProject();
  const projectName = project?.context?.project_name || project?.context?.name || 'unknown';
  
  const timestamp = new Date().toISOString();
  const ext = path.extname(filename);
  const commentChar = ext === '.py' ? '#' : '//';
  
  const metaHeader = `${commentChar} Generated by: Chat (Arcsi)
${commentChar} Project: ${projectName}
${commentChar} Knowledge-ID: ${knowledge_id || 'unknown'}
${commentChar} Created: ${timestamp}
${commentChar} Purpose: ${purpose || 'unknown'}
${commentChar} Status: experimental
${commentChar} ============================================

`;

  const fullContent = metaHeader + content;
  fs.writeFileSync(targetPath, fullContent, 'utf8');
  return { success: true, path: targetPath, message: `Mentve: ${targetPath}` };
});

registerTool('append_to_research_trace', async (input) => {
  const { knowledge_id, type, content, status, related, insight } = input;
  if (!knowledge_id || !content) return { error: 'Hianyzo parameter: knowledge_id, content' };

  const path = require('path');
  const fs = require('fs');
  const { RuntimeClient } = require('../runtimeClient');
  const rc = new RuntimeClient();
  const project = await rc.getActiveProject();
//  console.log('[TRACE DEBUG] aktiv projekt:', project?.context?.project_name || project?.context?.name);
  
  if (!project?.context) return { error: 'Nincs aktiv projekt' };
  
  const projectName = project.context.project_name || project.context.name;
  const contextPath = path.join(
    __dirname, '..', 'projects', 'my_projects', projectName, 'context.json'
  );
  
  if (!fs.existsSync(contextPath)) return { error: `Projekt context.json nem talalhato: ${contextPath}` };
  
  const d = JSON.parse(fs.readFileSync(contextPath, 'utf8'));
  if (!d.research_trace) return { error: 'Nincs research_trace a projektben' };
  
  const entry = {
    date: new Date().toISOString().split('T')[0],
    type: type || 'note',
    content,
    status: status || 'working',
    related: related || [],
    knowledge_id,
    insight: insight || '',
    added_by: 'chat_client'
  };
  
  d.research_trace.push(entry);
  fs.writeFileSync(contextPath, JSON.stringify(d, null, 2), 'utf8');
  
  return { success: true, knowledge_id, message: `Research trace bővítve: ${knowledge_id}` };
});

registerTool('file_write', async (input) => {
    const PROTECTED_FILES = ['.env', 'credentials.json', 'gmail_token.json'];
    const fileName = require('path').basename(input.path || '');
    if (PROTECTED_FILES.includes(fileName)) {
        return { error: `Vedett fajl, file_write tool-lal nem irhato: ${fileName}. Hasznald a Provider Setup Wizard-ot vagy kezi szerkesztest credential-modositashoz.` };
    }

    const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB
    if (input.content && Buffer.byteLength(input.content, 'utf8') > MAX_FILE_SIZE) {
        return { error: `A fájl mérete meghaladja a 10 MB-t.` };
    }
    if (!isPathAllowed(input.path)) return { error: `Tiltott útvonal: ${input.path}` };
    try {
        const dir = path.dirname(input.path);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

        // Rollback mentés - ha a fájl már létezik és nem append módban írunk
        let rollbackPath = null;
        if (!input.append && fs.existsSync(input.path)) {
            try {
                const rollbackDir = path.join(__dirname, '..', 'chat_logs', 'tool_rollback');
                if (!fs.existsSync(rollbackDir)) fs.mkdirSync(rollbackDir, { recursive: true });
                const safeName = input.path.replace(/[\/\\]/g, '_');
                const ts = Date.now();
                rollbackPath = path.join(rollbackDir, `${ts}_${safeName}`);
                fs.copyFileSync(input.path, rollbackPath);
            } catch (rbErr) {
                console.error('Rollback mentési hiba:', rbErr.message);
            }
        }

        const flag = input.append ? 'a' : 'w';
        fs.writeFileSync(input.path, input.content, { encoding: 'utf8', flag });
        return { success: true, path: input.path, append: !!input.append, rollback_saved: rollbackPath };
    } catch (e) { return { error: e.message }; }
});

registerTool('shell_exec', async (input) => {
    const FORBIDDEN_PATTERNS = [
        'rm\\s+-rf', 'rm\\s+-fr', 'mkfs', 'dd\\s+if', 'chmod\\s+777', 'chmod\\s+-R\\s+777',
        'curl.*passwd', 'wget.*passwd', 'cat\\s+/etc/passwd', 'cat\\s+/etc/shadow', 'cat\\s+/etc/sudoers',
        'su\\s+-', 'sudo\\s+su', 'nc\\s+-[le]', 'netcat.*-e', 'bash\\s+-i', '/dev/tcp', '/dev/udp',
        'eval\\s*\\(', 'exec\\s*\\(', 'source\\s+/etc', '\\|\\s*bash', '\\|\\s*sh', '`.*`', '\\$\\(.*\\)',
        '>&\\s*/dev/tcp', 'mkfifo', 'mknod', 'nohup', 'pkill\\s+-9', 'killall\\s+-9', ':\\(\\)\\s*\\{\\s*;',
        'export\\s+PATH', 'unset\\s+PATH', 'history\\s+-c', 'shred', 'wipe', 'blkid', 'fdisk', 'parted',
        'mount\\s+/dev', 'umount\\s+/', 'reboot', 'shutdown', 'poweroff', 'halt'
    ];
    const cmd = input.command;
    for (const pattern of FORBIDDEN_PATTERNS) {
        if (new RegExp(pattern, 'i').test(cmd)) {
            console.warn(`⚠️ Tiltott parancs blokkolva: ${cmd}`);
            return { error: `Tiltott parancs: ${cmd}` };
        }
    }
    try {
        const { exec } = require('child_process');
        const output = await new Promise((resolve, reject) => {
            const timeoutMs = input.timeout || 30000;
            const child = exec(cmd, {
                encoding: 'utf8',
                cwd: input.cwd || path.join(__dirname, '..'),
                maxBuffer: 10 * 1024 * 1024
            }, (err, stdout, stderr) => {
                if (err) {
                    err.stdout = stdout;
                    err.stderr = stderr;
                    return reject(err);
                }
                resolve(stdout);
            });

            const killer = setTimeout(() => {
                child.kill('SIGKILL');
                reject(new Error(`Parancs timeout (${timeoutMs / 1000}s): ${cmd}`));
            }, timeoutMs);

            child.on('exit', () => clearTimeout(killer));
        });
        return { stdout: output, returncode: 0 };
    } catch (e) {
        return { stdout: e.stdout || '', stderr: e.stderr || e.message, returncode: e.status || 1 };
    }
});

registerTool('http_request', async (input) => {
    if (!isUrlSafe(input.url)) return { error: `Nem biztonságos URL: ${input.url}` };
    const timeoutMs = input.timeout || 15000;
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
    try {
        const opts = {
            method: input.method || 'GET',
            headers: input.headers || {},
            signal: controller.signal
        };
        if (input.body) {
            opts.body = typeof input.body === 'string' ? input.body : JSON.stringify(input.body);
            opts.headers['Content-Type'] = opts.headers['Content-Type'] || 'application/json';
        }
        const resp = await fetch(input.url, opts);
        const text = await resp.text();
        return { status: resp.status, body: text.substring(0, 5000) };
    } catch (e) {
        if (e.name === 'AbortError') {
            return { error: `HTTP kérés timeout (${timeoutMs / 1000}s): ${input.url}` };
        }
        return { error: e.message };
    } finally {
        clearTimeout(timeoutId);
    }
});

registerTool('file_list', async (input) => {
    if (!input.path) return { error: 'Hiányzó path' };
    if (!isPathAllowed(input.path)) return { error: `Tiltott útvonal: ${input.path}` };
    try {
        const items = fs.readdirSync(input.path, { withFileTypes: true });
        const listing = items.map(item => ({
            name: item.name,
            type: item.isDirectory() ? 'dir' : 'file',
            size: item.isFile() ? fs.statSync(path.join(input.path, item.name)).size : 0
        }));
        return { files: listing, count: listing.length };
    } catch (e) { return { error: e.message }; }
});

registerTool('file_delete', async (input) => {
    if (!input.path) return { error: 'Hiányzó path' };
    if (!isPathAllowed(input.path)) return { error: `Tiltott útvonal: ${input.path}` };
    try {
        fs.unlinkSync(input.path);
        return { success: true, deleted: input.path };
    } catch (e) { return { error: e.message }; }
});

registerTool('calendar_create_event', async (input) => {
    try {
        const capabilityProfile = require('../utils/capabilityProfile');
        if (!capabilityProfile.isEnabled('calendar_integration')) {
            return { error: 'A naptár-integráció kikapcsolva a jelenlegi capability profile szerint' };
        }
    } catch (e) { /* capabilityProfile opcionális, hiba esetén engedjük át */ }

    try {
        const calendarClient = require('../calendarClient');
        if (!input.title || !input.date) {
            return { error: 'Hiányzó kötelező mező: title vagy date' };
        }
        const event = await calendarClient.createEvent({
            title: input.title,
            date: input.date,
            time: input.time || '09:00',
            durationMinutes: input.durationMinutes || 60,
            location: input.location || undefined,
            description: input.description || undefined
        });
        return { success: true, eventId: event.id, htmlLink: event.htmlLink, title: input.title, date: input.date, time: input.time };
    } catch (e) {
        return { error: e.message };
    }
});

registerTool('system_info', async (input) => {
    try {
        const os = require('os');
        return {
            hostname: os.hostname(),
            platform: os.platform(),
            uptime: os.uptime(),
            memory: { total: os.totalmem(), free: os.freemem(), used: os.totalmem() - os.freemem() },
            cpu: { cores: os.cpus().length, model: os.cpus()[0]?.model || 'unknown', load: os.loadavg() },
            homedir: os.homedir()
        };
    } catch (e) { return { error: e.message }; }
});

registerTool('rollback_restore', async (input) => {
    if (!input.target_file) return { error: 'Hiányzó target_file' };
    if (!isPathAllowed(input.target_file)) return { error: `Tiltott útvonal: ${input.target_file}` };

    try {
        const rollbackDir = path.join(__dirname, '..', 'chat_logs', 'tool_rollback');
        if (!fs.existsSync(rollbackDir)) {
            return { error: 'Backup nem található', ok: false };
        }

        const normalized = input.target_file.replace(/[\/\\]/g, '_');
        const allFiles = fs.readdirSync(rollbackDir);
        const matching = allFiles
            .filter(f => f.endsWith(normalized))
            .sort()
            .reverse();

        if (matching.length === 0) {
            return { error: 'Backup nem található', ok: false };
        }

        const latestBackup = matching[0];
        const backupPath = path.join(rollbackDir, latestBackup);

        if (!fs.existsSync(input.target_file)) {
            return { error: 'Eredeti fájl nem írható (nem létezik a cél mappa?)', ok: false };
        }

        // "Undo of undo" - a rollback előtti állapot is mentve
        const preRollbackTs = Date.now();
        const preRollbackName = `rollback_before_restore_${preRollbackTs}_${normalized}`;
        fs.copyFileSync(input.target_file, path.join(rollbackDir, preRollbackName));

        // Visszaállítás
        fs.copyFileSync(backupPath, input.target_file);

        return {
            ok: true,
            restored_from: latestBackup,
            pre_rollback_backup: preRollbackName,
            target_file: input.target_file
        };
    } catch (e) {
        return { error: e.message, ok: false };
    }
});

registerTool('instance_call', async (input) => {
    const { target, action, prompt } = input;
    if (!target) return { error: 'Hianyzo parameter: target (proxmox vagy phone)' };

    try {
        const path = require('path');
        require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
        const { delegateToProxmox, checkProxmoxHealth } = require('../instanceComm');

        if (target === 'proxmox') {
            if (action === 'health') {
                return await checkProxmoxHealth();
            }
            if (!prompt) return { error: 'Hianyzo parameter: prompt (mit kuldjunk a Proxmoxnak)' };
            const useAgent = (action === 'agent');
            return await delegateToProxmox({ prompt, sessionId: `instance_call_${Date.now()}`, useAgent });
        }

        return { error: `Ismeretlen target: ${target}. Hasznald: proxmox` };
    } catch (e) {
        return { error: e.message };
    }
});

// Home Assistant állapot lekérdezés tool
/*registerTool('ha_get_state', async (input) => {
    const HA_URL = process.env.HA_URL;
    const HA_TOKEN = process.env.HA_TOKEN;

    if (!HA_URL || !HA_TOKEN) {
        return { error: 'HA_URL vagy HA_TOKEN nincs beállítva a .env-ben' };
    }

    if (!input.entity_id) {
        return { error: 'Hiányzó entity_id paraméter' };
    }

    try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 10000);
        const res = await fetch(`${HA_URL}/api/states/${input.entity_id}`, {
            headers: {
                'Authorization': `Bearer ${HA_TOKEN}`,
                'Content-Type': 'application/json'
            },
            signal: controller.signal
        });
        clearTimeout(timeoutId);

        if (!res.ok) {
            return { error: `HA API hiba: ${res.status} - ${await res.text()}` };
        }

        const data = await res.json();
        return { success: true, entity_id: input.entity_id, state: data.state, attributes: data.attributes };
    } catch (e) {
        if (e.name === 'AbortError') {
            return { error: 'Időtúllépés a HA API válaszára várva' };
        }
        return { error: e.message };
    }
});
*/

module.exports = { toolRegistry, registerTool };
